# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crewgen/proto/crewgenerator.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!crewgen/proto/crewgenerator.proto\x12\x07\x63rewgen\"<\n\x17GenerateHtmlGameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"?\n\x18GenerateHtmlGameResponse\x12#\n\x04html\x18\x01 \x01(\x0b\x32\x15.crewgen.FileResponse\"\x1c\n\x0c\x46ileResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32h\n\rCrewGenerator\x12W\n\x10GenerateHtmlGame\x12 .crewgen.GenerateHtmlGameRequest\x1a!.crewgen.GenerateHtmlGameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crewgen.proto.crewgenerator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GENERATEHTMLGAMEREQUEST']._serialized_start=46
  _globals['_GENERATEHTMLGAMEREQUEST']._serialized_end=106
  _globals['_GENERATEHTMLGAMERESPONSE']._serialized_start=108
  _globals['_GENERATEHTMLGAMERESPONSE']._serialized_end=171
  _globals['_FILERESPONSE']._serialized_start=173
  _globals['_FILERESPONSE']._serialized_end=201
  _globals['_CREWGENERATOR']._serialized_start=203
  _globals['_CREWGENERATOR']._serialized_end=307
# @@protoc_insertion_point(module_scope)
